package com.testspace.test_smart_sec_school_proposer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SchDerived implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Travel Duration from School to Student postal code in KM")
	private java.lang.Float travelDuration;
	@org.kie.api.definition.type.Label(value = "Travel Distance from School to Student postal address")
	private java.lang.Float travelDistance;
	@org.kie.api.definition.type.Label(value = "CF of Express COP event")
	private java.lang.Integer copExCF;
	@org.kie.api.definition.type.Label(value = "CF of Express COP Rule")
	private java.lang.Integer copExRuleCF;
	@org.kie.api.definition.type.Label(value = "CF of CCA event")
	private java.lang.Integer ccaCF;
	@org.kie.api.definition.type.Label(value = "CF of CCA Rule")
	private java.lang.Integer ccaRuleCF;
	@org.kie.api.definition.type.Label(value = "CF of Normal Stream COP")
	private java.lang.Integer copNormalCF;
	@org.kie.api.definition.type.Label(value = "CF of Normal Stream Rule COP")
	private java.lang.Integer copNormalRuleCF;
	@org.kie.api.definition.type.Label(value = "CF of NT Stream COP")
	private java.lang.Integer copNTCF;
	@org.kie.api.definition.type.Label(value = "CF of COP NT Stream Rule")
	private java.lang.Integer copNTRuleCF;
	@org.kie.api.definition.type.Label(value = "CF of Mother Tongue event")
	private java.lang.Integer MTCF;
	@org.kie.api.definition.type.Label(value = "CF of Mother Tongue Rule")
	private java.lang.Integer MTRuleCF;
	@org.kie.api.definition.type.Label(value = "CF of Gender event")
	private java.lang.Integer genderCF;
	@org.kie.api.definition.type.Label(value = "CF of Gender Rule")
	private java.lang.Integer genderRuleCF;

	public SchDerived() {
	}

	public java.lang.Float getTravelDuration() {
		return this.travelDuration;
	}

	public void setTravelDuration(java.lang.Float travelDuration) {
		this.travelDuration = travelDuration;
	}

	public java.lang.Float getTravelDistance() {
		return this.travelDistance;
	}

	public void setTravelDistance(java.lang.Float travelDistance) {
		this.travelDistance = travelDistance;
	}

	public java.lang.Integer getCopExCF() {
		return this.copExCF;
	}

	public void setCopExCF(java.lang.Integer copExCF) {
		this.copExCF = copExCF;
	}

	public java.lang.Integer getCopExRuleCF() {
		return this.copExRuleCF;
	}

	public void setCopExRuleCF(java.lang.Integer copExRuleCF) {
		this.copExRuleCF = copExRuleCF;
	}

	public java.lang.Integer getCcaCF() {
		return this.ccaCF;
	}

	public void setCcaCF(java.lang.Integer ccaCF) {
		this.ccaCF = ccaCF;
	}

	public java.lang.Integer getCcaRuleCF() {
		return this.ccaRuleCF;
	}

	public void setCcaRuleCF(java.lang.Integer ccaRuleCF) {
		this.ccaRuleCF = ccaRuleCF;
	}

	public java.lang.Integer getCopNormalCF() {
		return this.copNormalCF;
	}

	public void setCopNormalCF(java.lang.Integer copNormalCF) {
		this.copNormalCF = copNormalCF;
	}

	public java.lang.Integer getCopNormalRuleCF() {
		return this.copNormalRuleCF;
	}

	public void setCopNormalRuleCF(java.lang.Integer copNormalRuleCF) {
		this.copNormalRuleCF = copNormalRuleCF;
	}

	public java.lang.Integer getCopNTCF() {
		return this.copNTCF;
	}

	public void setCopNTCF(java.lang.Integer copNTCF) {
		this.copNTCF = copNTCF;
	}

	public java.lang.Integer getCopNTRuleCF() {
		return this.copNTRuleCF;
	}

	public void setCopNTRuleCF(java.lang.Integer copNTRuleCF) {
		this.copNTRuleCF = copNTRuleCF;
	}

	public java.lang.Integer getMTCF() {
		return this.MTCF;
	}

	public void setMTCF(java.lang.Integer MTCF) {
		this.MTCF = MTCF;
	}

	public java.lang.Integer getMTRuleCF() {
		return this.MTRuleCF;
	}

	public void setMTRuleCF(java.lang.Integer MTRuleCF) {
		this.MTRuleCF = MTRuleCF;
	}

	public java.lang.Integer getGenderCF() {
		return this.genderCF;
	}

	public void setGenderCF(java.lang.Integer genderCF) {
		this.genderCF = genderCF;
	}

	public java.lang.Integer getGenderRuleCF() {
		return this.genderRuleCF;
	}

	public void setGenderRuleCF(java.lang.Integer genderRuleCF) {
		this.genderRuleCF = genderRuleCF;
	}

	public SchDerived(java.lang.Float travelDuration,
			java.lang.Float travelDistance, java.lang.Integer copExCF,
			java.lang.Integer copExRuleCF, java.lang.Integer ccaCF,
			java.lang.Integer ccaRuleCF, java.lang.Integer copNormalCF,
			java.lang.Integer copNormalRuleCF, java.lang.Integer copNTCF,
			java.lang.Integer copNTRuleCF, java.lang.Integer MTCF,
			java.lang.Integer MTRuleCF, java.lang.Integer genderCF,
			java.lang.Integer genderRuleCF) {
		this.travelDuration = travelDuration;
		this.travelDistance = travelDistance;
		this.copExCF = copExCF;
		this.copExRuleCF = copExRuleCF;
		this.ccaCF = ccaCF;
		this.ccaRuleCF = ccaRuleCF;
		this.copNormalCF = copNormalCF;
		this.copNormalRuleCF = copNormalRuleCF;
		this.copNTCF = copNTCF;
		this.copNTRuleCF = copNTRuleCF;
		this.MTCF = MTCF;
		this.MTRuleCF = MTRuleCF;
		this.genderCF = genderCF;
		this.genderRuleCF = genderRuleCF;
	}

}