package com.testspace.test_smart_sec_school_proposer;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("School Data Derived")
public class SchDerived implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Travel Duration from School to Student postal code in KM")
	private java.lang.Float travelDuration;
	@org.kie.api.definition.type.Label("Travel Distance from School to Student postal address")
	private java.lang.Float travelDistance;
	@org.kie.api.definition.type.Label("CF of Express COP event")
	private float copExCF;
	@org.kie.api.definition.type.Label("CF of Express COP Rule")
	private float copExRuleCF;
	@org.kie.api.definition.type.Label("CF of CCA event")
	private float ccaCF;
	@org.kie.api.definition.type.Label("CF of CCA Rule")
	private float ccaRuleCF;
	@org.kie.api.definition.type.Label("CF of Normal Stream COP")
	private float copNormalCF;
	@org.kie.api.definition.type.Label("CF of Normal Stream Rule COP")
	private float copNormalRuleCF;
	@org.kie.api.definition.type.Label("CF of NT Stream COP")
	private float copNTCF;
	@org.kie.api.definition.type.Label("CF of COP NT Stream Rule")
	private float copNTRuleCF;
	@org.kie.api.definition.type.Label("CF of Mother Tongue event")
	private float MTCF;
	@org.kie.api.definition.type.Label("CF of Mother Tongue Rule")
	private float MTRuleCF;
	@org.kie.api.definition.type.Label("CF of Gender event")
	private float genderCF;
	@org.kie.api.definition.type.Label("CF of Gender Rule")
	private float genderRuleCF;

	public SchDerived() {
	}

	public java.lang.Float getTravelDuration() {
		return this.travelDuration;
	}

	public void setTravelDuration(java.lang.Float travelDuration) {
		this.travelDuration = travelDuration;
	}

	public java.lang.Float getTravelDistance() {
		return this.travelDistance;
	}

	public void setTravelDistance(java.lang.Float travelDistance) {
		this.travelDistance = travelDistance;
	}

	public float getCopExCF() {
		return this.copExCF;
	}

	public void setCopExCF(float copExCF) {
		this.copExCF = copExCF;
	}

	public float getCopExRuleCF() {
		return this.copExRuleCF;
	}

	public void setCopExRuleCF(float copExRuleCF) {
		this.copExRuleCF = copExRuleCF;
	}

	public float getCcaCF() {
		return this.ccaCF;
	}

	public void setCcaCF(float ccaCF) {
		this.ccaCF = ccaCF;
	}

	public float getCcaRuleCF() {
		return this.ccaRuleCF;
	}

	public void setCcaRuleCF(float ccaRuleCF) {
		this.ccaRuleCF = ccaRuleCF;
	}

	public float getCopNormalCF() {
		return this.copNormalCF;
	}

	public void setCopNormalCF(float copNormalCF) {
		this.copNormalCF = copNormalCF;
	}

	public float getCopNormalRuleCF() {
		return this.copNormalRuleCF;
	}

	public void setCopNormalRuleCF(float copNormalRuleCF) {
		this.copNormalRuleCF = copNormalRuleCF;
	}

	public float getCopNTCF() {
		return this.copNTCF;
	}

	public void setCopNTCF(float copNTCF) {
		this.copNTCF = copNTCF;
	}

	public float getCopNTRuleCF() {
		return this.copNTRuleCF;
	}

	public void setCopNTRuleCF(float copNTRuleCF) {
		this.copNTRuleCF = copNTRuleCF;
	}

	public float getMTCF() {
		return this.MTCF;
	}

	public void setMTCF(float MTCF) {
		this.MTCF = MTCF;
	}

	public float getMTRuleCF() {
		return this.MTRuleCF;
	}

	public void setMTRuleCF(float MTRuleCF) {
		this.MTRuleCF = MTRuleCF;
	}

	public float getGenderCF() {
		return this.genderCF;
	}

	public void setGenderCF(float genderCF) {
		this.genderCF = genderCF;
	}

	public float getGenderRuleCF() {
		return this.genderRuleCF;
	}

	public void setGenderRuleCF(float genderRuleCF) {
		this.genderRuleCF = genderRuleCF;
	}

	public SchDerived(java.lang.Float travelDuration,
			java.lang.Float travelDistance, float copExCF, float copExRuleCF,
			float ccaCF, float ccaRuleCF, float copNormalCF,
			float copNormalRuleCF, float copNTCF, float copNTRuleCF,
			float MTCF, float MTRuleCF, float genderCF, float genderRuleCF) {
		this.travelDuration = travelDuration;
		this.travelDistance = travelDistance;
		this.copExCF = copExCF;
		this.copExRuleCF = copExRuleCF;
		this.ccaCF = ccaCF;
		this.ccaRuleCF = ccaRuleCF;
		this.copNormalCF = copNormalCF;
		this.copNormalRuleCF = copNormalRuleCF;
		this.copNTCF = copNTCF;
		this.copNTRuleCF = copNTRuleCF;
		this.MTCF = MTCF;
		this.MTRuleCF = MTRuleCF;
		this.genderCF = genderCF;
		this.genderRuleCF = genderRuleCF;
	}

}