package com.testspace.test_smart_sec_school_proposer;

import java.util.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path; 
import java.nio.file.Paths; 
import java.io.BufferedReader;
import java.io.IOException;
import java.net.URL;
import java.nio.charset.StandardCharsets;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SchoolCollection implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "School List")
	private java.util.List<com.testspace.test_smart_sec_school_proposer.School> schoolList;

	public SchoolCollection() {
       schoolList = new ArrayList<com.testspace.test_smart_sec_school_proposer.School>();
	}

	public java.util.List<com.testspace.test_smart_sec_school_proposer.School> getSchoolList() {
		return this.schoolList;
	}

	public void setSchoolList(
			java.util.List<com.testspace.test_smart_sec_school_proposer.School> schoolList) {
		this.schoolList = schoolList;
	}

	public SchoolCollection(
			java.util.List<com.testspace.test_smart_sec_school_proposer.School> schoolList) {
		this.schoolList = schoolList;
	}
	
	public void addSchool(School school){
	   
	    this.schoolList.add(school);
	}
	
	//Populate the school list from csv
	public void populateSchools(){
        //Load School from CSV
        
      	    
		Path pathToFile = Paths.get("SchoolDatas.csv");
	    try(BufferedReader br = Files.newBufferedReader(pathToFile, StandardCharsets.US_ASCII)) 
 
        { 
     		 String line = br.readLine(); 
     		 int j=0;
     	 	 while (line != null) { 
     	 	    String[] attributes = line.split(",");
     	 	    j++;
     	 	
      		    School school= createSchool(attributes); 
      			getSchoolList().add(school) ;
      	        line = br.readLine(); 
      	        }
        } 
  	   catch (IOException ioe) { 
  	   			ioe.printStackTrace(); 
  	   	} 
        
	}

    private static School createSchool(String[] metadata) 	{
		String schoolName = metadata[0]; 
		String postalCode = metadata[1]; 
    	String type = metadata[2]; 
		String motherTongue=metadata[3];
		String ccaListTemp=metadata[4];
		String schoolCode=metadata[5];
		String location= metadata[6];
		String fee=metadata[7];
		String programTypeOffered=metadata[8];
	    int copOverallMin=Integer.parseInt(metadata[9]);
		int copOverallMax=Integer.parseInt(metadata[10]);
		int copExpMin =Integer.parseInt(metadata[11]);
	    int copExpMean=Integer.parseInt(metadata[12]);
		int copExpMax=Integer.parseInt(metadata[13]);
		int copNormalMin=Integer.parseInt(metadata[14]);
		int copNormalMean=Integer.parseInt(metadata[15]);
		int copNormalMax=Integer.parseInt(metadata[16]);
		int copNTMin=Integer.parseInt(metadata[17]);
		int copNTMean=Integer.parseInt(metadata[18]);
		int copNTMax=Integer.parseInt(metadata[19]);
		String[] ccaList= ccaListTemp.split("%");
			
		
		 String ccaStr="";
		 for(int i=0;i<ccaList.length;i++) {
			  ccaStr =ccaStr+ccaList[i]+" ";
			}
		 
		School school = new School();
		school.setSchoolName(schoolName);
		school.setPostalCode(postalCode);
		school.setType(type);
		school.setMotherTongue(motherTongue);
		school.setCcaList(ccaStr);
		school.setSchoolCode(schoolCode);
		school.setLocation(location);
		school.setFee(fee);
		school.setProgramTypeOffered(programTypeOffered);
		school.setCopExpMin(copExpMin);
		school.setCopExpMean(copExpMean);
		school.setCopExpMax(copExpMax);
		school.setCopNormalMin(copNormalMin);
		school.setCopNormalMean(copNormalMean);
		school.setCopNormalMax(copNormalMax);
		school.setCopNTMin(copNTMin);
		school.setCopNTMean(copNTMean);
		school.setCopNTMax(copNTMax);
		school.setCopOverallMin(copOverallMin);
		school.setCopOverallMax(copOverallMax);
		school.setSchoolSelected(false);

		return school;
			 
	}
	
	public void sortSchoolCollection()
	{
	    System.out.println("inside sortSchoolCollection");
	    getSchoolList().sort(Comparator.comparing(School::getCopExpMean).reversed());
	      System.out.println("after sortSchoolCollection");
	}
	
	
	

}