package com.testspace.test_smart_sec_school_proposer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class School implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("School Name")
	private java.lang.String school_name;
	@org.kie.api.definition.type.Label("Location of School")
	private java.lang.String location;
	@org.kie.api.definition.type.Label("Postal Code")
	private java.lang.String postal_code;
	@org.kie.api.definition.type.Label("School Type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label("Mother Tongue")
	private java.lang.String motherTongue;
	@org.kie.api.definition.type.Label("List of CCAs")
	private java.lang.String ccaList;
	@org.kie.api.definition.type.Label("School Rank")
	private java.lang.String schoolRank;
	@org.kie.api.definition.type.Label("School Fee per month")
	private java.lang.String fee;

	@org.kie.api.definition.type.Label("School Code")
	private java.lang.String schoolCode;

	@org.kie.api.definition.type.Label("School Link")
	private java.lang.String schoolLink;

	@org.kie.api.definition.type.Label("Program Type Offered")
	private java.lang.String programTypeOffered;

	@org.kie.api.definition.type.Label("Subjects and Electives Offered")
	private java.lang.String subjectsOffered;

	@org.kie.api.definition.type.Label("Mean of Cutoff Point for Express stream")
	private java.lang.Integer copExpMean;

	@org.kie.api.definition.type.Label("Mean of Cutoff Point for NT stream")
	private java.lang.Integer copNTMean;

	@org.kie.api.definition.type.Label("Mean Cutoff Point for Normal stream")
	private java.lang.Integer copNormalMean;

	@org.kie.api.definition.type.Label("Min of Cutoff Point range for Express stream")
	private java.lang.Integer copExpMin;

	@org.kie.api.definition.type.Label("Min of Cutoff Point range for NT stream")
	private java.lang.Integer copNTMin;

	@org.kie.api.definition.type.Label("Min of Cutoff Point range for Normal stream")
	private java.lang.Integer copNormalMin;

	@org.kie.api.definition.type.Label("Max of Cutoff Point range for Express stream")
	private java.lang.Integer copExpMax;

	@org.kie.api.definition.type.Label("Max of Cutoff Point range for NT stream")
	private java.lang.Integer copNTMax;

	@org.kie.api.definition.type.Label("Max of Cutoff Point range for Normal stream")
	private java.lang.Integer copNormalMax;

	@org.kie.api.definition.type.Label("Min COP range of all stream")
	private java.lang.Integer copOverallMin;

	@org.kie.api.definition.type.Label("Max COP range of all stream")
	private java.lang.Integer copOverallMax;

	@org.kie.api.definition.type.Label("Mean COP range of Affiliated School for Express stream")
	private java.lang.Integer copExAffMean;

	@org.kie.api.definition.type.Label("Max COP range of Affiliated School for Express stream")
	private java.lang.Integer copExAffMax;

	@org.kie.api.definition.type.Label("Min COP range of Affiliated School for Normal stream")
	private java.lang.Integer copNormalAffMin;

	@org.kie.api.definition.type.Label("Mean COP range of Affiliated School for Normal stream")
	private java.lang.Integer copNormalAffMean;

	@org.kie.api.definition.type.Label("Max COP range of Affiliated School for Normal stream")
	private java.lang.Integer copNormalAffMax;

	@org.kie.api.definition.type.Label("Min COP range of Affiliated School for Express stream")
	private java.lang.Integer copExAffMin;

	@org.kie.api.definition.type.Label("Derived data of School")
	private com.testspace.test_smart_sec_school_proposer.SchDerived derivedData;

	@org.kie.api.definition.type.Label(value = "Set this variable if student COP matches school COP range")
	private java.lang.Boolean includeThisSchool;

	public School() {
	}

	public java.lang.String getSchool_name() {
		return this.school_name;
	}

	public void setSchool_name(java.lang.String school_name) {
		this.school_name = school_name;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.lang.String getPostal_code() {
		return this.postal_code;
	}

	public void setPostal_code(java.lang.String postal_code) {
		this.postal_code = postal_code;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getMotherTongue() {
		return this.motherTongue;
	}

	public void setMotherTongue(java.lang.String motherTongue) {
		this.motherTongue = motherTongue;
	}

	public java.lang.String getCcaList() {
		return this.ccaList;
	}

	public void setCcaList(java.lang.String ccaList) {
		this.ccaList = ccaList;
	}

	public java.lang.String getSchoolRank() {
		return this.schoolRank;
	}

	public void setSchoolRank(java.lang.String schoolRank) {
		this.schoolRank = schoolRank;
	}

	public java.lang.String getFee() {
		return this.fee;
	}

	public void setFee(java.lang.String fee) {
		this.fee = fee;
	}

	public java.lang.String getSchoolCode() {
		return this.schoolCode;
	}

	public void setSchoolCode(java.lang.String schoolCode) {
		this.schoolCode = schoolCode;
	}

	public java.lang.String getSchoolLink() {
		return this.schoolLink;
	}

	public void setSchoolLink(java.lang.String schoolLink) {
		this.schoolLink = schoolLink;
	}

	public java.lang.String getProgramTypeOffered() {
		return this.programTypeOffered;
	}

	public void setProgramTypeOffered(java.lang.String programTypeOffered) {
		this.programTypeOffered = programTypeOffered;
	}

	public java.lang.String getSubjectsOffered() {
		return this.subjectsOffered;
	}

	public void setSubjectsOffered(java.lang.String subjectsOffered) {
		this.subjectsOffered = subjectsOffered;
	}

	public java.lang.Integer getCopExpMean() {
		return this.copExpMean;
	}

	public void setCopExpMean(java.lang.Integer copExpMean) {
		this.copExpMean = copExpMean;
	}

	public java.lang.Integer getCopNTMean() {
		return this.copNTMean;
	}

	public void setCopNTMean(java.lang.Integer copNTMean) {
		this.copNTMean = copNTMean;
	}

	public java.lang.Integer getCopNormalMean() {
		return this.copNormalMean;
	}

	public void setCopNormalMean(java.lang.Integer copNormalMean) {
		this.copNormalMean = copNormalMean;
	}

	public java.lang.Integer getCopExpMin() {
		return this.copExpMin;
	}

	public void setCopExpMin(java.lang.Integer copExpMin) {
		this.copExpMin = copExpMin;
	}

	public java.lang.Integer getCopNTMin() {
		return this.copNTMin;
	}

	public void setCopNTMin(java.lang.Integer copNTMin) {
		this.copNTMin = copNTMin;
	}

	public java.lang.Integer getCopNormalMin() {
		return this.copNormalMin;
	}

	public void setCopNormalMin(java.lang.Integer copNormalMin) {
		this.copNormalMin = copNormalMin;
	}

	public java.lang.Integer getCopExpMax() {
		return this.copExpMax;
	}

	public void setCopExpMax(java.lang.Integer copExpMax) {
		this.copExpMax = copExpMax;
	}

	public java.lang.Integer getCopNTMax() {
		return this.copNTMax;
	}

	public void setCopNTMax(java.lang.Integer copNTMax) {
		this.copNTMax = copNTMax;
	}

	public java.lang.Integer getCopNormalMax() {
		return this.copNormalMax;
	}

	public void setCopNormalMax(java.lang.Integer copNormalMax) {
		this.copNormalMax = copNormalMax;
	}

	public java.lang.Integer getCopOverallMin() {
		return this.copOverallMin;
	}

	public void setCopOverallMin(java.lang.Integer copOverallMin) {
		this.copOverallMin = copOverallMin;
	}

	public java.lang.Integer getCopOverallMax() {
		return this.copOverallMax;
	}

	public void setCopOverallMax(java.lang.Integer copOverallMax) {
		this.copOverallMax = copOverallMax;
	}

	public java.lang.Integer getCopExAffMean() {
		return this.copExAffMean;
	}

	public void setCopExAffMean(java.lang.Integer copExAffMean) {
		this.copExAffMean = copExAffMean;
	}

	public java.lang.Integer getCopExAffMax() {
		return this.copExAffMax;
	}

	public void setCopExAffMax(java.lang.Integer copExAffMax) {
		this.copExAffMax = copExAffMax;
	}

	public java.lang.Integer getCopNormalAffMin() {
		return this.copNormalAffMin;
	}

	public void setCopNormalAffMin(java.lang.Integer copNormalAffMin) {
		this.copNormalAffMin = copNormalAffMin;
	}

	public java.lang.Integer getCopNormalAffMean() {
		return this.copNormalAffMean;
	}

	public void setCopNormalAffMean(java.lang.Integer copNormalAffMean) {
		this.copNormalAffMean = copNormalAffMean;
	}

	public java.lang.Integer getCopNormalAffMax() {
		return this.copNormalAffMax;
	}

	public void setCopNormalAffMax(java.lang.Integer copNormalAffMax) {
		this.copNormalAffMax = copNormalAffMax;
	}

	public java.lang.Integer getCopExAffMin() {
		return this.copExAffMin;
	}

	public void setCopExAffMin(java.lang.Integer copExAffMin) {
		this.copExAffMin = copExAffMin;
	}

	public com.testspace.test_smart_sec_school_proposer.SchDerived getDerivedData() {
		return this.derivedData;
	}

	public void setDerivedData(
			com.testspace.test_smart_sec_school_proposer.SchDerived derivedData) {
		this.derivedData = derivedData;
	}

	public java.lang.Boolean getIncludeThisSchool() {
		return this.includeThisSchool;
	}

	public void setIncludeThisSchool(java.lang.Boolean includeThisSchool) {
		this.includeThisSchool = includeThisSchool;
	}

	public School(
			java.lang.String school_name,
			java.lang.String location,
			java.lang.String postal_code,
			java.lang.String type,
			java.lang.String motherTongue,
			java.lang.String ccaList,
			java.lang.String schoolRank,
			java.lang.String fee,
			java.lang.String schoolCode,
			java.lang.String schoolLink,
			java.lang.String programTypeOffered,
			java.lang.String subjectsOffered,
			java.lang.Integer copExpMean,
			java.lang.Integer copNTMean,
			java.lang.Integer copNormalMean,
			java.lang.Integer copExpMin,
			java.lang.Integer copNTMin,
			java.lang.Integer copNormalMin,
			java.lang.Integer copExpMax,
			java.lang.Integer copNTMax,
			java.lang.Integer copNormalMax,
			java.lang.Integer copOverallMin,
			java.lang.Integer copOverallMax,
			java.lang.Integer copExAffMean,
			java.lang.Integer copExAffMax,
			java.lang.Integer copNormalAffMin,
			java.lang.Integer copNormalAffMean,
			java.lang.Integer copNormalAffMax,
			java.lang.Integer copExAffMin,
			com.testspace.test_smart_sec_school_proposer.SchDerived derivedData,
			java.lang.Boolean includeThisSchool) {
		this.school_name = school_name;
		this.location = location;
		this.postal_code = postal_code;
		this.type = type;
		this.motherTongue = motherTongue;
		this.ccaList = ccaList;
		this.schoolRank = schoolRank;
		this.fee = fee;
		this.schoolCode = schoolCode;
		this.schoolLink = schoolLink;
		this.programTypeOffered = programTypeOffered;
		this.subjectsOffered = subjectsOffered;
		this.copExpMean = copExpMean;
		this.copNTMean = copNTMean;
		this.copNormalMean = copNormalMean;
		this.copExpMin = copExpMin;
		this.copNTMin = copNTMin;
		this.copNormalMin = copNormalMin;
		this.copExpMax = copExpMax;
		this.copNTMax = copNTMax;
		this.copNormalMax = copNormalMax;
		this.copOverallMin = copOverallMin;
		this.copOverallMax = copOverallMax;
		this.copExAffMean = copExAffMean;
		this.copExAffMax = copExAffMax;
		this.copNormalAffMin = copNormalAffMin;
		this.copNormalAffMean = copNormalAffMean;
		this.copNormalAffMax = copNormalAffMax;
		this.copExAffMin = copExAffMin;
		this.derivedData = derivedData;
		this.includeThisSchool = includeThisSchool;
	}

}