package com.testspace.test_smart_sec_school_proposer;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Collection of School Objects")
public class SchoolCollection implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("List of School Record")
	private java.util.List<com.testspace.test_smart_sec_school_proposer.School> schoolList;
	public SchoolCollection() {
	}

	public java.util.List<com.testspace.test_smart_sec_school_proposer.School> getSchoolList() {
		return this.schoolList;
	}

	public void setSchoolList(
			java.util.List<com.testspace.test_smart_sec_school_proposer.School> schoolList) {
		this.schoolList = schoolList;
	}

	public SchoolCollection(
			java.util.List<com.testspace.test_smart_sec_school_proposer.School> schoolList) {
		this.schoolList = schoolList;
	}

}