package com.testspace.test_smart_sec_school_proposer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Student implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Student() {
    }




}